### ISSUE TITLE
Doesn't show agile boards

### ISSUE THREAD

**Issue by ferenci84** [kleder/timetracker#55]
## Expected Behavior
Boards should be loaded

## Actual Behavior
It hangs on loading boards

## Steps to Reproduce the Problem

  1. I set the token according to instructions. Url was given in this format: https://dynamicprogrammingsolutions.myjetbrains.com/youtrack/
  2. Account synced message was shown
  3. The spinner hangs on under title "Select agile boards"
  4. Clicking menu->workspace doesn't help, the spinner hangs on there on tab "Boards"

Note: I have special settings for some of my boards (custom columns and such), however I have a few boards set with defaults.

## Specifications

  - T-REC Version:
  - Platform: linux

**Comment by yogasw** [comment]
This is because the endpoints in use Timetracker to fetch Agile Boards list is outdated

**Comment by yogasw** [comment]
https://github.com/kleder/timetracker/blob/7ff66551b73b1070b4c4b74594cb7045f201ee27/src/app/services/api.service.ts#L100
This end point must be changed to ` /rest/admin/agiles`

**Comment by yogasw** [comment]
https://github.com/hanzhinstas/timetracker/releases

**Comment by rkorszun** [comment]
@arioki1 could you create a pull request?  I will merge it.

**Comment by arioki1** [comment]
I want to try to develop in my local, but always an error like this  @rkorszun 
```
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2779, in Load
    variables, includes, depth, check, True)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1296, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1311, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1270, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1149, in ProcessConditionsInDict
    variables, build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1289, in ProcessVariablesAndConditionsInDict
    build_file, key)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1296, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1315, in ProcessVariablesAndConditionsInList
    expanded = ExpandVariables(item, phase, variables, build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 914, in ExpandVariables
    sys.stderr.write(p_stderr)
TypeError: write() argument must be str, not bytes while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-62-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/qiscus/code/playground/timetracker/node_modules/@paulcbetts/system-idle-time
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN @angular-devkit/schematics@0.0.52 requires a peer of @angular-devkit/core@0.0.29 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/animations@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@4.4.3 requires a peer of @angular/platform-browser@4.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@4.4.3 requires a peer of @angular/platform-browser@4.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser@4.4.7 requires a peer of @angular/common@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@4.4.7 requires a peer of @angular/common@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@4.4.7 requires a peer of @angular/compiler@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@4.4.3 requires a peer of @angular/platform-browser@4.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/angular@0.0.49 requires a peer of @angular-devkit/schematics@0.0.34 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/electron-reload/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @paulcbetts/system-idle-time@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @paulcbetts/system-idle-time@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/qiscus/.npm/_logs/2020-07-21T12_45_55_997Z-debug.log

```

**Comment by yogasw** [comment]
I want to try to develop in my local, but always an error like this, @rkorszun 
```
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2779, in Load
    variables, includes, depth, check, True)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1296, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1311, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1270, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1149, in ProcessConditionsInDict
    variables, build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1289, in ProcessVariablesAndConditionsInDict
    build_file, key)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1296, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1315, in ProcessVariablesAndConditionsInList
    expanded = ExpandVariables(item, phase, variables, build_file)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 914, in ExpandVariables
    sys.stderr.write(p_stderr)
TypeError: write() argument must be str, not bytes while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-62-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/qiscus/code/playground/timetracker/node_modules/@paulcbetts/system-idle-time
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN @angular-devkit/schematics@0.0.52 requires a peer of @angular-devkit/core@0.0.29 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/animations@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@4.4.3 requires a peer of @angular/platform-browser@4.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@4.4.3 requires a peer of @angular/platform-browser@4.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser@4.4.7 requires a peer of @angular/common@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@4.4.7 requires a peer of @angular/common@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@4.4.7 requires a peer of @angular/compiler@4.4.7 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@4.4.3 requires a peer of @angular/platform-browser@4.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/angular@0.0.49 requires a peer of @angular-devkit/schematics@0.0.34 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/electron-reload/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @paulcbetts/system-idle-time@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @paulcbetts/system-idle-time@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/qiscus/.npm/_logs/2020-07-21T12_45_55_997Z-debug.log

```

**Comment by rkorszun** [comment]
@arioki1 I have still in progress version based on angular 10.0.4 and electron 9.11 (your error will be fixed inside), but I'm still fixing some breaks changes between the current version, I will also integrate your change in youtrack API URL and finally solve the never-ending loading.

btw. thanks for your precipitation

**Comment by yogasw** [comment]
@rkorszun In waiting for the latest version, when it has been released and problems are already fix maybe I can help when there is a problem

**Comment by rkorszun** [comment]
@arioki1 my current version is on https://github.com/kleder/timetracker/tree/release-1.4.0 right now the status is:

- [x] webpack build fixed
- [x] angular update done
- [ ] new api url integration 
- [ ] electron build fixing/ optimalization 
- [ ]  finally testings (test enabling)

**Comment by yogasw** [comment]
https://github.com/kleder/timetracker/tree/release-1.4.0
@rkorszun In this version I still find errors when NPM install, can you tell the versions of nodejs, npm, python and node-gyp that you're using?

**Comment by rkorszun** [comment]
@arioki1 I'm using on my device:
- node: 14.4.0
- npm: 6.14.4
- node-gyp: 6.0.1
- I have installed 2 versions of python (2.7.16 and 3.7.5)

I believe your error is more related with node-gyp itself, did you try to install node-gyp globally as mention in their documentation?

**Comment by yogasw** [comment]
@rkorszun  After I run  "npm npm run start " I get an error like this because the assets folder does not exist after running Webpack
![image](https://user-images.githubusercontent.com/1139881/88491706-40c42e00-cfcf-11ea-8f0c-ec233c688b3e.png)
